# Generated by Django 5.0.6 on 2024-07-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mysolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Solar_generation', models.CharField(max_length=9000)),
                ('Today_Production', models.CharField(max_length=8000)),
                ('Total_panels', models.CharField(max_length=5000)),
                ('Todays_efficiency', models.CharField(max_length=9000)),
                ('Monthly_Sales', models.CharField(max_length=9000)),
                ('Weather_prediction', models.CharField(max_length=9000)),
                ('inverter_Power_distribution', models.CharField(max_length=9000)),
                ('Performance', models.CharField(max_length=9000)),
                ('Hourly_temperature_and_humidity', models.CharField(max_length=9000)),
                ('Week_revenue', models.CharField(max_length=9000)),
            ],
        ),
    ]
